# Build stage
FROM node:20-alpine as frontend-build

WORKDIR /app

COPY src/frontend/package.json ./
RUN npm install

COPY src/frontend ./

# 👇 ADD THIS
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

# Runtime stage
FROM node:20-alpine as frontend

RUN npm install -g serve

WORKDIR /app

COPY --from=frontend-build /app/dist ./dist

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]